### ISSUE TITLE
[22112021 조웅] 날짜 작성 버그 식별

### ISSUE THREAD

**Issue by Wooong-E** [insung0-dklee/OSS_Account_2024-1#442]
1. 날짜 작성 시 월 부분에 12를 초과하는 수와 일 부분에 31을 초과하는 수에 대한 오류 처리 미흡 버그 식별.

2.  yyyy-mm-dd 와 yyyymmdd의 데이터가 따로 저장되어, 월별 보고서 생성 시, 같은 날짜임에도 다른 날짜로 인식하는 버그 식별.
 -> yyyy-mm-dd 와 yyyymmdd의 데이터가 같이 저장되게 하는 기능 추가 요청 or yyyymmdd 입력시 오류 처리 요청.

**Comment by insung0-dklee** [comment]
버그식별+1
