### ISSUE TITLE
[22112021 조웅] 강제 종료 버그 식별

### ISSUE THREAD

**Issue by Wooong-E** [insung0-dklee/OSS_Account_2024-1#443]
1. 회원가입을 한 데이터가 없을 시 로그인 기능을 실행하면 프로그램이 강제 종료되는 버그 식별.

2. 4: 예산 설정 및 초과 알림 실행 시 예산 지출 설정 금액에 숫자를 제외한 입력 시 프로그램이 강제 종료되는 버그 식별.

**Comment by insung0-dklee** [comment]
버그식별+1
