### ISSUE TITLE
[22012156박규민]메모장 저장이후 읽기 오류 식별

### ISSUE THREAD

**Issue by gyumin123** [insung0-dklee/OSS_Account_2024-1#512]
![화면 캡처 2024-06-05 011816](https://github.com/insung0-dklee/OSS_Account_2024-1/assets/165123802/6c48e1d3-dc1a-43e7-a896-28d6fd37ac26)

코드 395번째줄부터의 오류인것같다. 해결노력해보았지만 실패했다.

**Comment by insung0-dklee** [comment]
버그식별+1
