### ISSUE TITLE
[22112093 이택민] 556번 라인 KeyError

### ISSUE THREAD

**Issue by imTeakMin** [insung0-dklee/OSS_Account_2024-1#515]
with open('login.txt', 'w', encoding='UTF-8') as fw: 
            for user_id, user_info in userdata2.items():  
                friends_str = ", ".join(user_info["friends"])
이 부분에서 userdata2[id] = {'pw': pw_data, 'name': name, 'phone': phone}에 'friends'라는 key,value 값이 없어서 
friends_str = ", ".join(user_info["friends"]) 이 부분에서 오류가 뜨는 것 같습니다.

**Comment by insung0-dklee** [comment]
버그식별 +1
